accelerate launch --mixed_precision="fp16"  --multi_gpu train.py \
  --pretrained_model_name_or_path='CompVis/stable-diffusion-v1-4' \
  --dataset_name=None \
  --use_ema \
  --resolution=512 --center_crop --random_flip \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --gradient_checkpointing \
  --max_train_steps=15000 \
  --learning_rate=1e-05 \
  --max_grad_norm=1 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --output_dir="sd-model" \
  --push_to_hub \
  --hub_token=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 \
  --enable_xformers_memory_efficient_attention \
  --validation_prompts=None \
  --checkpointing_steps=3000 